# Generated by Django 5.2.13 on 2026-04-15 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название упражнения')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('lower_is_better', models.BooleanField(default=False, verbose_name='Меньше результат — лучше?')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ступень (например, I ступень)')),
                ('gender', models.CharField(choices=[('M', 'М'), ('F', 'Ж')], max_length=1, verbose_name='Пол')),
                ('age_min', models.IntegerField()),
                ('age_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Normative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.FloatField()),
                ('silver', models.FloatField()),
                ('bronze', models.FloatField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exercise')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norms', to='api.step')),
            ],
        ),
    ]
