# Generated by Django 5.2.13 on 2026-04-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normative',
            name='is_mandatory',
            field=models.BooleanField(default=True, verbose_name='Обязательное испытание'),
        ),
    ]
