# Generated by Django 5.2.13 on 2026-04-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_normative_is_mandatory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'Упражнение', 'verbose_name_plural': 'Упражнения'},
        ),
        migrations.AlterModelOptions(
            name='normative',
            options={'verbose_name': 'Норматив', 'verbose_name_plural': 'Нормативы'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'verbose_name': 'Ступень', 'verbose_name_plural': 'Ступени'},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='lower_is_better',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='unit',
        ),
        migrations.AddField(
            model_name='normative',
            name='lower_is_better',
            field=models.BooleanField(default=True, verbose_name='Меньше = лучше (бег)'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название упражнения'),
        ),
        migrations.AlterField(
            model_name='normative',
            name='is_mandatory',
            field=models.BooleanField(default=True, verbose_name='Обязательно'),
        ),
        migrations.AlterField(
            model_name='step',
            name='age_max',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='step',
            name='age_min',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='step',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название ступени'),
        ),
    ]
