# Generated by Django 5.2.13 on 2026-04-17 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_exercise_options_alter_normative_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normative',
            name='lower_is_better',
        ),
        migrations.AddField(
            model_name='normative',
            name='is_higher_better',
            field=models.BooleanField(default=False, verbose_name='Больше = лучше (для отжиманий/прыжков)'),
        ),
        migrations.AlterField(
            model_name='normative',
            name='bronze',
            field=models.FloatField(verbose_name='Бронза'),
        ),
        migrations.AlterField(
            model_name='normative',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exercise', verbose_name='Упражнение'),
        ),
        migrations.AlterField(
            model_name='normative',
            name='gold',
            field=models.FloatField(verbose_name='Золото'),
        ),
        migrations.AlterField(
            model_name='normative',
            name='silver',
            field=models.FloatField(verbose_name='Серебро'),
        ),
        migrations.AlterField(
            model_name='normative',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norms', to='api.step', verbose_name='Ступень'),
        ),
    ]
