# Generated by Django 5.2.13 on 2026-04-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_normative_lower_is_better_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={},
        ),
        migrations.AddField(
            model_name='step',
            name='bronze_mandatory',
            field=models.IntegerField(default=4, verbose_name='Обязательных для Бронзы'),
        ),
        migrations.AddField(
            model_name='step',
            name='bronze_optional',
            field=models.IntegerField(default=1, verbose_name='Выборных для Бронзы'),
        ),
        migrations.AddField(
            model_name='step',
            name='gold_mandatory',
            field=models.IntegerField(default=4, verbose_name='Обязательных для Золота'),
        ),
        migrations.AddField(
            model_name='step',
            name='gold_optional',
            field=models.IntegerField(default=2, verbose_name='Выборных для Золота'),
        ),
        migrations.AddField(
            model_name='step',
            name='silver_mandatory',
            field=models.IntegerField(default=4, verbose_name='Обязательных для Серебра'),
        ),
        migrations.AddField(
            model_name='step',
            name='silver_optional',
            field=models.IntegerField(default=1, verbose_name='Выборных для Серебра'),
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
