# Generated by Django 6.0.5 on 2026-05-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_participantlist_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='uin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='УИН'),
        ),
    ]
