# Generated by Django 5.2.13 on 2026-05-08 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_participant_uin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField(verbose_name='Результат')),
                ('result_date', models.DateField(verbose_name='Дата сдачи')),
                ('medal', models.CharField(choices=[('gold', 'Золото'), ('silver', 'Серебро'), ('bronze', 'Бронза'), ('none', 'Без знака')], default='none', max_length=10, verbose_name='Знак отличия')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Обязательное испытание')),
                ('protocol_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер протокола')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exercise', verbose_name='Упражнение')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='api.participant', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Результат испытания',
                'verbose_name_plural': 'Результаты испытаний',
                'ordering': ['-result_date', 'participant'],
                'unique_together': {('participant', 'exercise', 'result_date')},
            },
        ),
    ]
