# Generated by Django 5.2.13 on 2026-05-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_testresult'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together=set(),
        ),
    ]
