# Generated by Django 5.2.13 on 2026-07-15 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('create_list', 'Создание списка'), ('delete_list', 'Удаление списка'), ('save_list', 'Сохранение списка'), ('edit_list', 'Редактирование списка'), ('export_federal', 'Выгрузка федерального шаблона'), ('create_user', 'Создание пользователя'), ('edit_user', 'Редактирование пользователя'), ('delete_user', 'Удаление пользователя'), ('change_role', 'Смена роли пользователя'), ('view_list', 'Просмотр списка'), ('view_home', 'Просмотр главной страницы')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('target_name', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Журнал действий',
                'verbose_name_plural': 'Журналы действий',
                'ordering': ['-created_at'],
            },
        ),
    ]
